// API CALLS
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// SIGN UP
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// SIGN IN
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
export const EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED";

// SIGN OUT
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

// RESET PASSWORD
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_ERROR = "RESET_ERROR";

// ADD COIN
export const ADD_COIN_SUCCESS = "ADD_COIN_SUCCESS";
export const ADD_COIN_ERROR = "ADD_COIN_ERROR";

// REMOVE COIN
export const REMOVE_COIN_SUCCESS = "REMOVE_COIN_SUCCESS";
export const REMOVE_COIN_ERROR = "REMOVE_COIN_ERROR";

// GET COIN DATA FROM COIN GECKO API
export const FETCH_COIN_DATA_ERROR = "FETCH_COIN_DATA_ERROR";

// UPDATE SEARCH FOR COINS
export const UPDATE_SEARCH_SUCCESS = "UPDATE_SEARCH_SUCCESS";
export const UPDATE_SEARCH_ERROR = "UPDATE_SEARCH_ERROR";

// GET COIN GECKO KEYS FOR ALL COINS
export const UPDATE_COIN_GECKO_KEYS_SUCCESS = "UPDATE_COIN_GECKO_KEYS_SUCCESS";
export const UPDATE_COIN_GECKO_KEYS_ERROR = "UPDATE_COIN_GECKO_KEYS_ERROR";

// SELECT WATCH LIST COIN
export const SELECTED_WATCH_LIST_COIN_SUCCESS = "SELECTED_WATCH_LIST_COIN_SUCCESS";
export const DISPLAY_WATCH_LIST_SUCCESS = "DISPLAY_COIN_DATA_SUCCESS";

// UPDATE WATCH LIST
export const UPDATE_WATCH_LIST_SUCCESS = "UPDATE_WATCH_LIST_SUCCESS"
